### PR TITLE
upgrade umd condition for video heartbeat sdk

### PR DESCRIPTION
**Pull request by huozhi**
next.js make `window.module` available on client bundle and they just removed yesterday (not released) https://github.com/zeit/next.js/pull/5093/files

so in the old versions of next.js pages, sometimes `window.module` is `{}` and `window.module.exports` is `undefined` or `{}`;
the condition `&& module.exports` is not trustable

so adobe sdk cannot mount itself on window but on `window.module.exports`.

in commonJS, global.exports is avaible, so we just upgrade the umd check condition.
latest umd checking: https://github.com/umdjs/umd/blob/master/templates/commonjsStrictGlobal.js

### CODE REVIEW

**Comment by huozhi** [comment]
@praveek

**Comment by praveek** [comment]
Yes. Our current library only works with node like environments with supports module.exports. We are tracking this internally and will add support to stricter CommonJS environments with our next browser release. 

We can not directly merge this PR as the repo only tracks releases. 

Thanks,
Praveen

**Comment by huozhi** [comment]
@praveek thanks for your explanation. we can just hold this PR until the release is ready then. may I get notified when the change is settle down?

**Comment by praveek** [comment]
Yes. I will notify you when our release is ready. We can keep this PR open till then.

**Comment by praveek** [comment]
This has been fixed in 2.1.1 version of our JS library (https://github.com/Adobe-Marketing-Cloud/video-heartbeat-v2/releases/tag/js-v2.1.1)

**Comment by huozhi** [comment]
awesome @praveek ! gonna close this PR

**Pull request closed without merging**
